# Site settings
title: "Loja de Peças para PCs Gamers"
description: "Descubra os melhores componentes para seu setup gamer."
url: "https://carlos2007henrique.github.io"
baseurl: ""

# Build settings
markdown: kramdown
highlighter: rouge
theme: minima

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - vendor/
  - .bundle/
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - .bundle